version: "3.8"

services:
  redis:
    restart: unless-stopped
    image: 'redis:alpine'
    volumes:
        - './data/redis:/data'
    ports:
        - '6579:6379'
    command: >
          --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  app:
    build: .
    restart: unless-stopped
    container_name: app
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - 5000:5000
    environment:
      - redis_url=redis://:${REDIS_PASSWORD}@redis:6379
    healthcheck:
      test: curl --fail http://localhost:5000/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s  
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    healthcheck:
      test: curl --fail http://localhost:9090/healthy || exit 1
      interval: 200s
      timeout: 200s
      retries: 5    