global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "app"

rule_files:

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app"
    metrics_path: '/prom-metrics'
    static_configs:
      - targets: ['app:5000']
        labels:
          group: 'production'

    dns_sd_configs:
      - names: ["app"]
        port: 5000
        type: A
        refresh_interval: 5s